name: Playwright Tests and Artillery Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  # Job 1: Ejecuta las pruebas de Playwright
    playwright-tests:
      name: Run Playwright Tests
      timeout-minutes: 60
      runs-on: ubuntu-latest

      steps:
        # 1. Clona el repositorio
          - name: Checkout code
            uses: actions/checkout@v4

        # 2. Configura Node.js (versión LTS)
          - name: Setup Node.js 
            uses: actions/setup-node@v4
            with:
              node-version: lts/*

        # 3. Instala las dependencias del proyecto
          - name: Install dependencies
            run: npm ci

        # 4. Instala los navegadores requeridos por Playwright
          - name: Install Playwright Browsers
            run: npx playwright install --with-deps

        # 5. Ejecuta las pruebas de Playwright usando el script definido en package.json
          - name: Run Playwright tests
            run: npm run pw

        # 6. Publica el reporte de Playwright como artefacto
          - name: Upload Playwright report
            uses: actions/upload-artifact@v4
            if: ${{ !cancelled() }}
            with:
              name: playwright-report
              path: playwright-report/
              retention-days: 30

  # Job 2: Ejecuta las pruebas de carga con Artillery
    artillery-tests:
      name: Run Artillery Load Tests
      runs-on: ubuntu-latest
      timeout-minutes: 60

      steps:
        # 1. Clona el repositorio
        - name: Checkout code
          uses: actions/checkout@v4

        # 2. Configura Node.js (versión LTS)
        - name: Setup Node.js
          uses: actions/setup-node@v4
          with:
            node-version: lts/*

        # 3. Instala las dependencias del proyecto
        - name: Install dependencies
          run: npm ci

        # 4. Ejecuta la prueba de carga con Artillery y genera el reporte
        - name: Run Artillery load test
          run: npm run load-test-report

        # 5. Publica el reporte de Artillery como artefacto
        - name: Upload Artillery report
          uses: actions/upload-artifact@v4
          if: ${{ !cancelled() }}
          with:
            name: artillery-report
            path: report.json
            retention-days: 30